/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSpieltagRouteImport } from './routes/_authenticated/spieltag'
import { Route as AuthenticatedKontoRouteImport } from './routes/_authenticated/konto'
import { Route as AuthenticatedKaderRouteImport } from './routes/_authenticated/kader'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAufstiegstopfRouteImport } from './routes/_authenticated/aufstiegstopf'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSpieltagRoute = AuthenticatedSpieltagRouteImport.update({
  id: '/spieltag',
  path: '/spieltag',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKontoRoute = AuthenticatedKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKaderRoute = AuthenticatedKaderRouteImport.update({
  id: '/kader',
  path: '/kader',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAufstiegstopfRoute =
  AuthenticatedAufstiegstopfRouteImport.update({
    id: '/aufstiegstopf',
    path: '/aufstiegstopf',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aufstiegstopf': typeof AuthenticatedAufstiegstopfRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/kader': typeof AuthenticatedKaderRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/spieltag': typeof AuthenticatedSpieltagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aufstiegstopf': typeof AuthenticatedAufstiegstopfRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/kader': typeof AuthenticatedKaderRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/spieltag': typeof AuthenticatedSpieltagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/aufstiegstopf': typeof AuthenticatedAufstiegstopfRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/_authenticated/kader': typeof AuthenticatedKaderRoute
  '/_authenticated/konto': typeof AuthenticatedKontoRoute
  '/_authenticated/spieltag': typeof AuthenticatedSpieltagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aufstiegstopf'
    | '/dashboard'
    | '/einstellungen'
    | '/kader'
    | '/konto'
    | '/spieltag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aufstiegstopf'
    | '/dashboard'
    | '/einstellungen'
    | '/kader'
    | '/konto'
    | '/spieltag'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/aufstiegstopf'
    | '/_authenticated/dashboard'
    | '/_authenticated/einstellungen'
    | '/_authenticated/kader'
    | '/_authenticated/konto'
    | '/_authenticated/spieltag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/spieltag': {
      id: '/_authenticated/spieltag'
      path: '/spieltag'
      fullPath: '/spieltag'
      preLoaderRoute: typeof AuthenticatedSpieltagRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/konto': {
      id: '/_authenticated/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof AuthenticatedKontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kader': {
      id: '/_authenticated/kader'
      path: '/kader'
      fullPath: '/kader'
      preLoaderRoute: typeof AuthenticatedKaderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aufstiegstopf': {
      id: '/_authenticated/aufstiegstopf'
      path: '/aufstiegstopf'
      fullPath: '/aufstiegstopf'
      preLoaderRoute: typeof AuthenticatedAufstiegstopfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAufstiegstopfRoute: typeof AuthenticatedAufstiegstopfRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRoute
  AuthenticatedKaderRoute: typeof AuthenticatedKaderRoute
  AuthenticatedKontoRoute: typeof AuthenticatedKontoRoute
  AuthenticatedSpieltagRoute: typeof AuthenticatedSpieltagRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAufstiegstopfRoute: AuthenticatedAufstiegstopfRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRoute,
  AuthenticatedKaderRoute: AuthenticatedKaderRoute,
  AuthenticatedKontoRoute: AuthenticatedKontoRoute,
  AuthenticatedSpieltagRoute: AuthenticatedSpieltagRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
